version: "3.9"

services:
  web:
    build: .
    image: mohamedcamara2002/my-angular-app:latest
    container_name: my-angular-web
    ports:
      - "8080:80"
    restart: unless-stopped
    networks:
      - app_net

networks:
  app_net:
    driver: bridge